apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-s3-cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-s3-cleaner
  template:
    metadata:
      labels:
        app: web-s3-cleaner
    spec:
      # serviceAccountName: web-s3-cleaner # uncomment and bind IAM role if using IRSA
      containers:
        - name: app
          image: your-docker-repo/web-s3-cleaner:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: S3_BUCKETS
              value: "bucket-a,bucket-b" # comma-separated allowed buckets
            - name: AWS_REGION
              value: "us-east-1"
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

